nama=("HERVINA HALIMI")
nim=("SI202300")
semester=int(2)
ttl=("Lanji,30-08-2005")
umur=int(18)
jeniskelamin=("Perempuan")
agama=("Islam")
alamat=("Dusun Bogo Desa Darmaji")
hp=("+6281945939637")
status=("Mahasiswa")
email=("elvina170799@gmail.com")
sd=("SDN 1 DARMAJI")
smp=("SMPN 2 KOPANG")
sma=("SMAN 1 PRAYA TENGAH")
kuliah=("SEKOLAH TINGGI MANAJEMEN INFORMASI DAN KOMUNIKASI LOMBOK")

print("======================================")
print("--SELAMAT DATANG DI CURRICULUM VITAE--")
print("======================================")
print("-----------------DATA PRIBAADI-----------------")
print("Nama : ",nama)
print("NIM : ",nim)
print("Tempat,Tanggal Lahir : ",ttl)
print("Umur : ",umur)
print("Jenis Kelamin : ",jeniskelamin)
print("Agama : ",agama)
print("Alamat: ",alamat)
print("Nomor HP : ",hp)
print("Status : ",status)
print("Semester : ",semester)
print("E_mail : ",email)
print("-----------------PENDIDIKAN-----------------")
print("SD : ",sd)
print("SMP : ",smp)
print("SMA : ",sma)
print(" Perguruan tinggi : ",kuliah)
print("===============================")
print("PROGRAM SELSAI DAN TERIMA KASIH")
print("===============================")